# This playbook is meant to provision a new computer.
# Run with: ansible-playbook -i hosts.yml provision.arch.yml --ask-pass --ask-become-pass
# Install ansible using
#   sudo pacman -Sy ansible

---
- name: Provision a machine.
  hosts: arch-dummy
  become_method: sudo
  tasks:
    - name: Core Setup
      ansible.builtin.include_role:
        name: core

    - name: Install yay deps
      become: yes
      ansible.builtin.package:
        name: base-devel,git,go
        state: latest

    - name: Clone and build yay
      shell: 'cd /tmp && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm'
      args:
        creates: /usr/bin/yay

    - name: Dotfiles
      ansible.builtin.include_role:
        name: dotfiles

    - name: Install i3 wm
      ansible.builtin.include_role:
        name: i3

    - name: Install apps
      ansible.builtin.include_role:
        name: apps

    - name: Install dev tools
      ansible.builtin.include_role:
        name: dev
