- name: Install Fontforge
  become: yes
  ansible.builtin.package:
    name: fontforge

- name: Install gitflow
  yay: 
    name: gitflow-avh
    state: latest

- name: Install brave browser
  yay: 
    name: brave-bin
    state: latest

- name: Install VSCodium
  yay: 
    name: vscodium-bin
    state: latest

- name: Install nvm
  ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: /home/{{ user.stdout }}/.nvm/nvm.sh

- name: Install rvm
  ansible.builtin.shell: |
    gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    \curl -sSL https://get.rvm.io | bash -s stable
  # creates: /home/{{ user.stdout }}/.nvm/nvm.sh
