- name: Get the username running the deploy
  become: false
  local_action: command whoami
  register: user
- debug: 
    msg: "Default user is {{ user.stdout }}"
- name: Distribution
  debug:
    msg: "Distribution is {{ ansible_distribution }}"

- name: Install git and zsh
  become: true
  ansible.builtin.package:
    name: git,zsh,neofetch
    state: latest

- name: Install cli tools
  become: true
  ansible.builtin.package:
    name: vim,wget,trash-cli
    state: latest

- name: Install less
  become: true
  ansible.builtin.package:
    name: less
    state: latest

- name: Change shell to ZSH
  become: true
  shell: chsh -s $(which zsh) mikol

- name: Install SSH server - Arch
  become: true
  ansible.builtin.package:
    name: openssh-server
    state: latest
  when: ansible_facts['distribution'] == "Arch" 

- name: Install SSH server - Debian
  become: true
  ansible.builtin.package:
    name: openssh-server
    state: latest
  when: ansible_facts['distribution'] == "Debian" or
    ansible_facts['distribution'] == "Raspbian"

- name: Enable SSH server
  become: true
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started

- name: Install fonts - Arch
  become: true
  ansible.builtin.package:
    name: ttf-firacode-nerd,otf-firamono-nerd,ttf-jetbrains-mono
    state: latest
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install Fira Code - Debian
  become: true
  ansible.builtin.package:
    name: fonts-firacode
    state: latest
  when: ansible_facts['distribution'] == "Debian" or
    ansible_facts['distribution'] == "Raspbian"

- name: Install Jetbrains Mono - Debian
  become: true
  ansible.builtin.package:
    name: fonts-jetbrains-mono
    state: latest
  when: ansible_facts['distribution'] == "Debian" or
    ansible_facts['distribution'] == "Raspbian"

- name: Disable Root Login
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: true
  notify:
    - Restart ssh
