- name: Install keychain
  ansible.builtin.package:
    name: keychain
    state: latest
  become: true

- name: Install Oh-my-zsh
  become: false
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: '/home/{{ user.stdout }}/.oh-my-zsh/oh-my-zsh.sh'

- name: Clone dot files
  ansible.builtin.git:
    repo: 'https://github.com/mikolfaro/dotfiles.git'
    dest: '/home/{{ user.stdout }}/dotfiles'
  
- name: Setup dot files
  ansible.builtin.copy:
    src: '/home/{{ user.stdout }}/dotfiles/'
    dest: '/home/{{ user.stdout }}/'
    remote_src: true

- name: Use kitty as terminal emulator - Raspbian
  ansible.builtin.replace:
    path: "/home/{{ user.stdout }}/.config/i3/config"
    regexp: '(\s+)alacritty(\s+.*)?$'
    replace: '\1kitty\2'
  when: ansible_facts['architecture'] == "aarch64"

- name: Delete git directory
  ansible.builtin.file:
    path: '/home/{{ user.stdout }}/.git'
    state: absent

- name: Delete provision directory
  ansible.builtin.file:
    path: '/home/{{ user.stdout }}/provision'
    state: absent
